version: '3.6'
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:
  # postgresql-db:
  #   image: postgres:11-alpine
  #   environment:
  #     - POSTGRES_DB=argo
  #     - POSTGRES_USER=argo
  #     - POSTGRES_PASSWORD=secret
  #     volumes:
  #       - ./db-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  mongodb:
    image: mongo:4.2.3-bionic
    # networks:
    # - myapp
    command: mongod --port 27018
    volumes:
      - ./db-data:/data/db
    ports:
      - '27018:27018'

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
